[package]
name = "mini-mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
eyre = "0.6.11"
deku = "0.16"
tokio = { version = "1.35.1", features = ["full"] }
